help:		## Print Help Message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//

frontend:	## Install Frontend Component
 	@sh components/frontend.sh

catalogue:	## Install Catalogue Component
	@sh components/catalogue.sh


